---
version: "2"

services:
  alpine:
    image: ez123/docker-ops-toolbox-cli-db:alpine-edge
    build:
      context: ./src.base
      dockerfile: Dockerfile.ubuntu1604

  ubuntu:
    image: ez123/docker-ops-toolbox-cli-db:ubuntu-1804
    build:
      context: ./src.base
      dockerfile: Dockerfile.ubuntu1804
